spring:
  datasource:
    url: ${SPRING_CONFIG_BD_URL:jdbc:postgresql://ec2-50-19-114-27.compute-1.amazonaws.com:5432/ddg2t9ctfp9q0k}
    username: ${SPRING_CONFIG_BD_USERNAME:wgiddgjtkuaomv}
    password: ${SPRING_CONFIG_BD_PASSWORD:984ed929561b45afe6f92ed44a535df402a21ab02f6f7b67836ac236972bdb80}
    hiraki:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
    com:
      pdr: TRACE
