package com.pdr.common.entity;
// Generated 24-04-2020 11:25:23 by Hibernate Tools 5.4.12.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	private BigInteger idApplication;
	private Images images;
	private ApplicationType applicationType;
	private String name;
	private String description;
	private String url;
	private String packageName;
	private Date createDate;
	private BigInteger createUser;
	private Date updateDate;
	private BigInteger updateUser;
	private Character valid;
	private Set profileApplications = new HashSet(0);

	public Application() {
	}

	public Application(BigInteger idApplication, ApplicationType applicationType, String name, String description,
			Date createDate, BigInteger createUser) {
		this.idApplication = idApplication;
		this.applicationType = applicationType;
		this.name = name;
		this.description = description;
		this.createDate = createDate;
		this.createUser = createUser;
	}

	public Application(BigInteger idApplication, Images images, ApplicationType applicationType, String name,
			String description, String url, String packageName, Date createDate, BigInteger createUser, Date updateDate,
			BigInteger updateUser, Character valid, Set profileApplications) {
		this.idApplication = idApplication;
		this.images = images;
		this.applicationType = applicationType;
		this.name = name;
		this.description = description;
		this.url = url;
		this.packageName = packageName;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.valid = valid;
		this.profileApplications = profileApplications;
	}

	public BigInteger getIdApplication() {
		return this.idApplication;
	}

	public void setIdApplication(BigInteger idApplication) {
		this.idApplication = idApplication;
	}

	public Images getImages() {
		return this.images;
	}

	public void setImages(Images images) {
		this.images = images;
	}

	public ApplicationType getApplicationType() {
		return this.applicationType;
	}

	public void setApplicationType(ApplicationType applicationType) {
		this.applicationType = applicationType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public BigInteger getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(BigInteger createUser) {
		this.createUser = createUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public BigInteger getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(BigInteger updateUser) {
		this.updateUser = updateUser;
	}

	public Character getValid() {
		return this.valid;
	}

	public void setValid(Character valid) {
		this.valid = valid;
	}

	public Set getProfileApplications() {
		return this.profileApplications;
	}

	public void setProfileApplications(Set profileApplications) {
		this.profileApplications = profileApplications;
	}

}
