package com.pdr.common.entity;
// Generated 24-04-2020 11:25:23 by Hibernate Tools 5.4.12.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationType generated by hbm2java
 */
public class ApplicationType implements java.io.Serializable {

	private BigInteger idApplicationType;
	private String name;
	private Set applications = new HashSet(0);

	public ApplicationType() {
	}

	public ApplicationType(BigInteger idApplicationType, String name) {
		this.idApplicationType = idApplicationType;
		this.name = name;
	}

	public ApplicationType(BigInteger idApplicationType, String name, Set applications) {
		this.idApplicationType = idApplicationType;
		this.name = name;
		this.applications = applications;
	}

	public BigInteger getIdApplicationType() {
		return this.idApplicationType;
	}

	public void setIdApplicationType(BigInteger idApplicationType) {
		this.idApplicationType = idApplicationType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getApplications() {
		return this.applications;
	}

	public void setApplications(Set applications) {
		this.applications = applications;
	}

}
