package com.pdr.common.entity;
// Generated 24-04-2020 11:25:23 by Hibernate Tools 5.4.12.Final

import java.math.BigInteger;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * Images generated by hbm2java
 */
public class Images implements java.io.Serializable {

	private BigInteger idImage;
	private Blob content;
	private String ext;
	private String name;
	private Set applications = new HashSet(0);

	public Images() {
	}

	public Images(BigInteger idImage, String ext, String name) {
		this.idImage = idImage;
		this.ext = ext;
		this.name = name;
	}

	public Images(BigInteger idImage, Blob content, String ext, String name, Set applications) {
		this.idImage = idImage;
		this.content = content;
		this.ext = ext;
		this.name = name;
		this.applications = applications;
	}

	public BigInteger getIdImage() {
		return this.idImage;
	}

	public void setIdImage(BigInteger idImage) {
		this.idImage = idImage;
	}

	public Blob getContent() {
		return this.content;
	}

	public void setContent(Blob content) {
		this.content = content;
	}

	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getApplications() {
		return this.applications;
	}

	public void setApplications(Set applications) {
		this.applications = applications;
	}

}
