package com.pdr.common.entity;
// Generated 24-04-2020 11:25:23 by Hibernate Tools 5.4.12.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private BigInteger idProfile;
	private String name;
	private Date createDate;
	private BigInteger createUser;
	private Date updateDate;
	private BigInteger updateUser;
	private char valid;
	private Set profileApplications = new HashSet(0);
	private Set userProfiles = new HashSet(0);
	private Set userProfileExts = new HashSet(0);

	public Profile() {
	}

	public Profile(BigInteger idProfile, String name, Date createDate, BigInteger createUser, char valid) {
		this.idProfile = idProfile;
		this.name = name;
		this.createDate = createDate;
		this.createUser = createUser;
		this.valid = valid;
	}

	public Profile(BigInteger idProfile, String name, Date createDate, BigInteger createUser, Date updateDate,
			BigInteger updateUser, char valid, Set profileApplications, Set userProfiles, Set userProfileExts) {
		this.idProfile = idProfile;
		this.name = name;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.valid = valid;
		this.profileApplications = profileApplications;
		this.userProfiles = userProfiles;
		this.userProfileExts = userProfileExts;
	}

	public BigInteger getIdProfile() {
		return this.idProfile;
	}

	public void setIdProfile(BigInteger idProfile) {
		this.idProfile = idProfile;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public BigInteger getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(BigInteger createUser) {
		this.createUser = createUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public BigInteger getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(BigInteger updateUser) {
		this.updateUser = updateUser;
	}

	public char getValid() {
		return this.valid;
	}

	public void setValid(char valid) {
		this.valid = valid;
	}

	public Set getProfileApplications() {
		return this.profileApplications;
	}

	public void setProfileApplications(Set profileApplications) {
		this.profileApplications = profileApplications;
	}

	public Set getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(Set userProfiles) {
		this.userProfiles = userProfiles;
	}

	public Set getUserProfileExts() {
		return this.userProfileExts;
	}

	public void setUserProfileExts(Set userProfileExts) {
		this.userProfileExts = userProfileExts;
	}

}
