package com.pdr.common.entity;
// Generated 24-04-2020 11:25:23 by Hibernate Tools 5.4.12.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * ProfileSubApplication generated by hbm2java
 */
public class ProfileSubApplication implements java.io.Serializable {

	private BigInteger idProfileSubApplication;
	private ProfileApplication profileApplication;
	private BigInteger idSubApplicationMenu;
	private BigInteger ordercolumn;
	private Date createDate;
	private BigInteger createUser;
	private Date updateDate;
	private BigInteger updateUser;

	public ProfileSubApplication() {
	}

	public ProfileSubApplication(BigInteger idProfileSubApplication, ProfileApplication profileApplication,
			BigInteger idSubApplicationMenu, BigInteger ordercolumn, Date createDate, BigInteger createUser) {
		this.idProfileSubApplication = idProfileSubApplication;
		this.profileApplication = profileApplication;
		this.idSubApplicationMenu = idSubApplicationMenu;
		this.ordercolumn = ordercolumn;
		this.createDate = createDate;
		this.createUser = createUser;
	}

	public ProfileSubApplication(BigInteger idProfileSubApplication, ProfileApplication profileApplication,
			BigInteger idSubApplicationMenu, BigInteger ordercolumn, Date createDate, BigInteger createUser,
			Date updateDate, BigInteger updateUser) {
		this.idProfileSubApplication = idProfileSubApplication;
		this.profileApplication = profileApplication;
		this.idSubApplicationMenu = idSubApplicationMenu;
		this.ordercolumn = ordercolumn;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	public BigInteger getIdProfileSubApplication() {
		return this.idProfileSubApplication;
	}

	public void setIdProfileSubApplication(BigInteger idProfileSubApplication) {
		this.idProfileSubApplication = idProfileSubApplication;
	}

	public ProfileApplication getProfileApplication() {
		return this.profileApplication;
	}

	public void setProfileApplication(ProfileApplication profileApplication) {
		this.profileApplication = profileApplication;
	}

	public BigInteger getIdSubApplicationMenu() {
		return this.idSubApplicationMenu;
	}

	public void setIdSubApplicationMenu(BigInteger idSubApplicationMenu) {
		this.idSubApplicationMenu = idSubApplicationMenu;
	}

	public BigInteger getOrdercolumn() {
		return this.ordercolumn;
	}

	public void setOrdercolumn(BigInteger ordercolumn) {
		this.ordercolumn = ordercolumn;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public BigInteger getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(BigInteger createUser) {
		this.createUser = createUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public BigInteger getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(BigInteger updateUser) {
		this.updateUser = updateUser;
	}

}
