package com.pdr.common.entity;
// Generated 24-04-2020 11:25:23 by Hibernate Tools 5.4.12.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * SubMenuApplication generated by hbm2java
 */
public class SubMenuApplication implements java.io.Serializable {

	private BigInteger idSubApplicationMenu;
	private String name;
	private String description;
	private String url;
	private Date createDate;
	private BigInteger createUser;
	private Date updateDate;
	private BigInteger updateUser;
	private Character valid;
	private String icon;
	private String datatarget;

	public SubMenuApplication() {
	}

	public SubMenuApplication(BigInteger idSubApplicationMenu, String name, String description, Date createDate,
			BigInteger createUser) {
		this.idSubApplicationMenu = idSubApplicationMenu;
		this.name = name;
		this.description = description;
		this.createDate = createDate;
		this.createUser = createUser;
	}

	public SubMenuApplication(BigInteger idSubApplicationMenu, String name, String description, String url,
			Date createDate, BigInteger createUser, Date updateDate, BigInteger updateUser, Character valid,
			String icon, String datatarget) {
		this.idSubApplicationMenu = idSubApplicationMenu;
		this.name = name;
		this.description = description;
		this.url = url;
		this.createDate = createDate;
		this.createUser = createUser;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
		this.valid = valid;
		this.icon = icon;
		this.datatarget = datatarget;
	}

	public BigInteger getIdSubApplicationMenu() {
		return this.idSubApplicationMenu;
	}

	public void setIdSubApplicationMenu(BigInteger idSubApplicationMenu) {
		this.idSubApplicationMenu = idSubApplicationMenu;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public BigInteger getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(BigInteger createUser) {
		this.createUser = createUser;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public BigInteger getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(BigInteger updateUser) {
		this.updateUser = updateUser;
	}

	public Character getValid() {
		return this.valid;
	}

	public void setValid(Character valid) {
		this.valid = valid;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getDatatarget() {
		return this.datatarget;
	}

	public void setDatatarget(String datatarget) {
		this.datatarget = datatarget;
	}

}
