package com.pdr.common.entity;
// Generated 24-04-2020 11:25:23 by Hibernate Tools 5.4.12.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private BigInteger idUser;
	private String fullName;
	private String rut;
	private String email;
	private String password;
	private String username;
	private BigInteger administrator;
	private BigInteger valid;
	private Set userProfiles = new HashSet(0);

	public Users() {
	}

	public Users(BigInteger idUser, String fullName, String password, BigInteger administrator, BigInteger valid) {
		this.idUser = idUser;
		this.fullName = fullName;
		this.password = password;
		this.administrator = administrator;
		this.valid = valid;
	}

	public Users(BigInteger idUser, String fullName, String rut, String email, String password, String username,
			BigInteger administrator, BigInteger valid, Set userProfiles) {
		this.idUser = idUser;
		this.fullName = fullName;
		this.rut = rut;
		this.email = email;
		this.password = password;
		this.username = username;
		this.administrator = administrator;
		this.valid = valid;
		this.userProfiles = userProfiles;
	}

	public BigInteger getIdUser() {
		return this.idUser;
	}

	public void setIdUser(BigInteger idUser) {
		this.idUser = idUser;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public BigInteger getAdministrator() {
		return this.administrator;
	}

	public void setAdministrator(BigInteger administrator) {
		this.administrator = administrator;
	}

	public BigInteger getValid() {
		return this.valid;
	}

	public void setValid(BigInteger valid) {
		this.valid = valid;
	}

	public Set getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(Set userProfiles) {
		this.userProfiles = userProfiles;
	}

}
