package com.pdr.common.entity;
// Generated 24-04-2020 11:25:23 by Hibernate Tools 5.4.12.Final

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * UserExt generated by hbm2java
 */
public class UserExt implements java.io.Serializable {

	private BigInteger idUserExt;
	private BigInteger idBusinessExt;
	private String username;
	private String password;
	private String fullName;
	private String rut;
	private String email;
	private BigInteger valid;
	private Set userProfileExts = new HashSet(0);

	public UserExt() {
	}

	public UserExt(BigInteger idUserExt, BigInteger idBusinessExt, String username, String password, String fullName,
			BigInteger valid) {
		this.idUserExt = idUserExt;
		this.idBusinessExt = idBusinessExt;
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.valid = valid;
	}

	public UserExt(BigInteger idUserExt, BigInteger idBusinessExt, String username, String password, String fullName,
			String rut, String email, BigInteger valid, Set userProfileExts) {
		this.idUserExt = idUserExt;
		this.idBusinessExt = idBusinessExt;
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.rut = rut;
		this.email = email;
		this.valid = valid;
		this.userProfileExts = userProfileExts;
	}

	public BigInteger getIdUserExt() {
		return this.idUserExt;
	}

	public void setIdUserExt(BigInteger idUserExt) {
		this.idUserExt = idUserExt;
	}

	public BigInteger getIdBusinessExt() {
		return this.idBusinessExt;
	}

	public void setIdBusinessExt(BigInteger idBusinessExt) {
		this.idBusinessExt = idBusinessExt;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public BigInteger getValid() {
		return this.valid;
	}

	public void setValid(BigInteger valid) {
		this.valid = valid;
	}

	public Set getUserProfileExts() {
		return this.userProfileExts;
	}

	public void setUserProfileExts(Set userProfileExts) {
		this.userProfileExts = userProfileExts;
	}

}
