package com.pdr.common.corredora.entity;
// Generated 29-09-2020 15:26:18 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CorrVenta generated by hbm2java
 */
@Entity
@Table(name = "CORR_VENTA", schema = "CDORA")
public class CorrVenta implements java.io.Serializable {

	private int idOperacion;
	private Date fechaVenta;
	private String canalVenta;
	private Long rutPasaporte;
	private long rutVendedor;
	private Character clienteParque;
	private String parque;
	private String NContrato;
	private String estadoContrato;
	private String email;
	private Character dvRut;
	private Character dvRutVendedor;
	private String NCertCobertura;
	private String NPoliza;
	private Date fechaVigencia;
	private Short edadActuarial;
	private Long NPropuesta;
	private String estado;
	private String motivo;
	private Date fechaEstado;
	private Date fechaCarga;
	private String NPolizaPlan;
	private String canal;
	private Boolean envioParque;
	private Long NFolio;
	private String rutC;
	private String rutV;
	private String rutT;
	private BigDecimal parque20;
	private Integer idPlan;
	private Integer idCanal;
	private Integer idSubCanal;
	private BigDecimal SFolio;
	private BigDecimal SContrato;

	public CorrVenta() {
	}

	public CorrVenta(int idOperacion, long rutVendedor) {
		this.idOperacion = idOperacion;
		this.rutVendedor = rutVendedor;
	}

	public CorrVenta(int idOperacion, Date fechaVenta, String canalVenta, Long rutPasaporte, long rutVendedor,
			Character clienteParque, String parque, String NContrato, String estadoContrato, String email,
			Character dvRut, Character dvRutVendedor, String NCertCobertura, String NPoliza, Date fechaVigencia,
			Short edadActuarial, Long NPropuesta, String estado, String motivo, Date fechaEstado, Date fechaCarga,
			String NPolizaPlan, String canal, Boolean envioParque, Long NFolio, String rutC, String rutV, String rutT,
			BigDecimal parque20, Integer idPlan, Integer idCanal, Integer idSubCanal, BigDecimal SFolio,
			BigDecimal SContrato) {
		this.idOperacion = idOperacion;
		this.fechaVenta = fechaVenta;
		this.canalVenta = canalVenta;
		this.rutPasaporte = rutPasaporte;
		this.rutVendedor = rutVendedor;
		this.clienteParque = clienteParque;
		this.parque = parque;
		this.NContrato = NContrato;
		this.estadoContrato = estadoContrato;
		this.email = email;
		this.dvRut = dvRut;
		this.dvRutVendedor = dvRutVendedor;
		this.NCertCobertura = NCertCobertura;
		this.NPoliza = NPoliza;
		this.fechaVigencia = fechaVigencia;
		this.edadActuarial = edadActuarial;
		this.NPropuesta = NPropuesta;
		this.estado = estado;
		this.motivo = motivo;
		this.fechaEstado = fechaEstado;
		this.fechaCarga = fechaCarga;
		this.NPolizaPlan = NPolizaPlan;
		this.canal = canal;
		this.envioParque = envioParque;
		this.NFolio = NFolio;
		this.rutC = rutC;
		this.rutV = rutV;
		this.rutT = rutT;
		this.parque20 = parque20;
		this.idPlan = idPlan;
		this.idCanal = idCanal;
		this.idSubCanal = idSubCanal;
		this.SFolio = SFolio;
		this.SContrato = SContrato;
	}

	@Id

	@Column(name = "ID_OPERACION", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdOperacion() {
		return this.idOperacion;
	}

	public void setIdOperacion(int idOperacion) {
		this.idOperacion = idOperacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_VENTA", length = 7)
	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	@Column(name = "CANAL_VENTA", length = 50)
	public String getCanalVenta() {
		return this.canalVenta;
	}

	public void setCanalVenta(String canalVenta) {
		this.canalVenta = canalVenta;
	}

	@Column(name = "RUT_PASAPORTE", precision = 10, scale = 0)
	public Long getRutPasaporte() {
		return this.rutPasaporte;
	}

	public void setRutPasaporte(Long rutPasaporte) {
		this.rutPasaporte = rutPasaporte;
	}

	@Column(name = "RUT_VENDEDOR", nullable = false, precision = 10, scale = 0)
	public long getRutVendedor() {
		return this.rutVendedor;
	}

	public void setRutVendedor(long rutVendedor) {
		this.rutVendedor = rutVendedor;
	}

	@Column(name = "CLIENTE_PARQUE", length = 1)
	public Character getClienteParque() {
		return this.clienteParque;
	}

	public void setClienteParque(Character clienteParque) {
		this.clienteParque = clienteParque;
	}

	@Column(name = "PARQUE", length = 10)
	public String getParque() {
		return this.parque;
	}

	public void setParque(String parque) {
		this.parque = parque;
	}

	@Column(name = "N_CONTRATO", length = 20)
	public String getNContrato() {
		return this.NContrato;
	}

	public void setNContrato(String NContrato) {
		this.NContrato = NContrato;
	}

	@Column(name = "ESTADO_CONTRATO", length = 3)
	public String getEstadoContrato() {
		return this.estadoContrato;
	}

	public void setEstadoContrato(String estadoContrato) {
		this.estadoContrato = estadoContrato;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DV_RUT", length = 1)
	public Character getDvRut() {
		return this.dvRut;
	}

	public void setDvRut(Character dvRut) {
		this.dvRut = dvRut;
	}

	@Column(name = "DV_RUT_VENDEDOR", length = 1)
	public Character getDvRutVendedor() {
		return this.dvRutVendedor;
	}

	public void setDvRutVendedor(Character dvRutVendedor) {
		this.dvRutVendedor = dvRutVendedor;
	}

	@Column(name = "N_CERT_COBERTURA", length = 20)
	public String getNCertCobertura() {
		return this.NCertCobertura;
	}

	public void setNCertCobertura(String NCertCobertura) {
		this.NCertCobertura = NCertCobertura;
	}

	@Column(name = "N_POLIZA", length = 20)
	public String getNPoliza() {
		return this.NPoliza;
	}

	public void setNPoliza(String NPoliza) {
		this.NPoliza = NPoliza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_VIGENCIA", length = 7)
	public Date getFechaVigencia() {
		return this.fechaVigencia;
	}

	public void setFechaVigencia(Date fechaVigencia) {
		this.fechaVigencia = fechaVigencia;
	}

	@Column(name = "EDAD_ACTUARIAL", precision = 4, scale = 0)
	public Short getEdadActuarial() {
		return this.edadActuarial;
	}

	public void setEdadActuarial(Short edadActuarial) {
		this.edadActuarial = edadActuarial;
	}

	@Column(name = "N_PROPUESTA", precision = 10, scale = 0)
	public Long getNPropuesta() {
		return this.NPropuesta;
	}

	public void setNPropuesta(Long NPropuesta) {
		this.NPropuesta = NPropuesta;
	}

	@Column(name = "ESTADO", length = 20)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "MOTIVO")
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_ESTADO", length = 7)
	public Date getFechaEstado() {
		return this.fechaEstado;
	}

	public void setFechaEstado(Date fechaEstado) {
		this.fechaEstado = fechaEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_CARGA", length = 7)
	public Date getFechaCarga() {
		return this.fechaCarga;
	}

	public void setFechaCarga(Date fechaCarga) {
		this.fechaCarga = fechaCarga;
	}

	@Column(name = "N_POLIZA_PLAN", length = 20)
	public String getNPolizaPlan() {
		return this.NPolizaPlan;
	}

	public void setNPolizaPlan(String NPolizaPlan) {
		this.NPolizaPlan = NPolizaPlan;
	}

	@Column(name = "CANAL", length = 20)
	public String getCanal() {
		return this.canal;
	}

	public void setCanal(String canal) {
		this.canal = canal;
	}

	@Column(name = "ENVIO_PARQUE", precision = 1, scale = 0)
	public Boolean getEnvioParque() {
		return this.envioParque;
	}

	public void setEnvioParque(Boolean envioParque) {
		this.envioParque = envioParque;
	}

	@Column(name = "N_FOLIO", precision = 10, scale = 0)
	public Long getNFolio() {
		return this.NFolio;
	}

	public void setNFolio(Long NFolio) {
		this.NFolio = NFolio;
	}

	@Column(name = "RUT_C", length = 20)
	public String getRutC() {
		return this.rutC;
	}

	public void setRutC(String rutC) {
		this.rutC = rutC;
	}

	@Column(name = "RUT_V", length = 20)
	public String getRutV() {
		return this.rutV;
	}

	public void setRutV(String rutV) {
		this.rutV = rutV;
	}

	@Column(name = "RUT_T", length = 20)
	public String getRutT() {
		return this.rutT;
	}

	public void setRutT(String rutT) {
		this.rutT = rutT;
	}

	@Column(name = "PARQUE_20", precision = 22, scale = 0)
	public BigDecimal getParque20() {
		return this.parque20;
	}

	public void setParque20(BigDecimal parque20) {
		this.parque20 = parque20;
	}

	@Column(name = "ID_PLAN", precision = 5, scale = 0)
	public Integer getIdPlan() {
		return this.idPlan;
	}

	public void setIdPlan(Integer idPlan) {
		this.idPlan = idPlan;
	}

	@Column(name = "ID_CANAL", precision = 5, scale = 0)
	public Integer getIdCanal() {
		return this.idCanal;
	}

	public void setIdCanal(Integer idCanal) {
		this.idCanal = idCanal;
	}

	@Column(name = "ID_SUB_CANAL", precision = 5, scale = 0)
	public Integer getIdSubCanal() {
		return this.idSubCanal;
	}

	public void setIdSubCanal(Integer idSubCanal) {
		this.idSubCanal = idSubCanal;
	}

	@Column(name = "S_FOLIO", precision = 22, scale = 0)
	public BigDecimal getSFolio() {
		return this.SFolio;
	}

	public void setSFolio(BigDecimal SFolio) {
		this.SFolio = SFolio;
	}

	@Column(name = "S_CONTRATO", precision = 22, scale = 0)
	public BigDecimal getSContrato() {
		return this.SContrato;
	}

	public void setSContrato(BigDecimal SContrato) {
		this.SContrato = SContrato;
	}

}
