package com.pdr.common.corredora.entity;
// Generated 29-09-2020 15:26:18 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorrComunaId generated by hbm2java
 */
@Embeddable
public class CorrComunaId implements java.io.Serializable {

	private int idComuna;
	private int idCiudad;

	public CorrComunaId() {
	}

	public CorrComunaId(int idComuna, int idCiudad) {
		this.idComuna = idComuna;
		this.idCiudad = idCiudad;
	}

	@Column(name = "ID_COMUNA", nullable = false, precision = 5, scale = 0)
	public int getIdComuna() {
		return this.idComuna;
	}

	public void setIdComuna(int idComuna) {
		this.idComuna = idComuna;
	}

	@Column(name = "ID_CIUDAD", nullable = false, precision = 5, scale = 0)
	public int getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(int idCiudad) {
		this.idCiudad = idCiudad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorrComunaId))
			return false;
		CorrComunaId castOther = (CorrComunaId) other;

		return (this.getIdComuna() == castOther.getIdComuna()) && (this.getIdCiudad() == castOther.getIdCiudad());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdComuna();
		result = 37 * result + this.getIdCiudad();
		return result;
	}

}
