package com.pdr.common.corredora.entity;
// Generated 29-09-2020 15:26:18 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CorrVentaDireccion generated by hbm2java
 */
@Entity
@Table(name = "CORR_VENTA_DIRECCION", schema = "CDORA")
public class CorrVentaDireccion implements java.io.Serializable {

	private int idDireccion;
	private short tipoDireccion;
	private Integer idOperacion;
	private Integer idComuna;
	private Integer idCiudad;
	private String descripcion;
	private String idTipo;
	private String mail;
	private BigDecimal idRegion;

	public CorrVentaDireccion() {
	}

	public CorrVentaDireccion(int idDireccion, short tipoDireccion) {
		this.idDireccion = idDireccion;
		this.tipoDireccion = tipoDireccion;
	}

	public CorrVentaDireccion(int idDireccion, short tipoDireccion, Integer idOperacion, Integer idComuna,
			Integer idCiudad, String descripcion, String idTipo, String mail, BigDecimal idRegion) {
		this.idDireccion = idDireccion;
		this.tipoDireccion = tipoDireccion;
		this.idOperacion = idOperacion;
		this.idComuna = idComuna;
		this.idCiudad = idCiudad;
		this.descripcion = descripcion;
		this.idTipo = idTipo;
		this.mail = mail;
		this.idRegion = idRegion;
	}

	@Id

	@Column(name = "ID_DIRECCION", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(int idDireccion) {
		this.idDireccion = idDireccion;
	}

	@Column(name = "TIPO_DIRECCION", nullable = false, precision = 3, scale = 0)
	public short getTipoDireccion() {
		return this.tipoDireccion;
	}

	public void setTipoDireccion(short tipoDireccion) {
		this.tipoDireccion = tipoDireccion;
	}

	@Column(name = "ID_OPERACION", precision = 8, scale = 0)
	public Integer getIdOperacion() {
		return this.idOperacion;
	}

	public void setIdOperacion(Integer idOperacion) {
		this.idOperacion = idOperacion;
	}

	@Column(name = "ID_COMUNA", precision = 5, scale = 0)
	public Integer getIdComuna() {
		return this.idComuna;
	}

	public void setIdComuna(Integer idComuna) {
		this.idComuna = idComuna;
	}

	@Column(name = "ID_CIUDAD", precision = 5, scale = 0)
	public Integer getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(Integer idCiudad) {
		this.idCiudad = idCiudad;
	}

	@Column(name = "DESCRIPCION", length = 80)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ID_TIPO", length = 20)
	public String getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(String idTipo) {
		this.idTipo = idTipo;
	}

	@Column(name = "MAIL", length = 50)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "ID_REGION", precision = 22, scale = 0)
	public BigDecimal getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(BigDecimal idRegion) {
		this.idRegion = idRegion;
	}

}
