package com.pdr.common.corredora.entity;
// Generated 29-09-2020 15:26:18 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CorrVentaTelefono generated by hbm2java
 */
@Entity
@Table(name = "CORR_VENTA_TELEFONO", schema = "CDORA")
public class CorrVentaTelefono implements java.io.Serializable {

	private int idTelefono;
	private short tipoTelefono;
	private Integer idOperacion;
	private String telefono;
	private String preTelefono;
	private String idTipo;
	private String telefono2;
	private String movil;

	public CorrVentaTelefono() {
	}

	public CorrVentaTelefono(int idTelefono, short tipoTelefono) {
		this.idTelefono = idTelefono;
		this.tipoTelefono = tipoTelefono;
	}

	public CorrVentaTelefono(int idTelefono, short tipoTelefono, Integer idOperacion, String telefono,
			String preTelefono, String idTipo, String telefono2, String movil) {
		this.idTelefono = idTelefono;
		this.tipoTelefono = tipoTelefono;
		this.idOperacion = idOperacion;
		this.telefono = telefono;
		this.preTelefono = preTelefono;
		this.idTipo = idTipo;
		this.telefono2 = telefono2;
		this.movil = movil;
	}

	@Id

	@Column(name = "ID_TELEFONO", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdTelefono() {
		return this.idTelefono;
	}

	public void setIdTelefono(int idTelefono) {
		this.idTelefono = idTelefono;
	}

	@Column(name = "TIPO_TELEFONO", nullable = false, precision = 3, scale = 0)
	public short getTipoTelefono() {
		return this.tipoTelefono;
	}

	public void setTipoTelefono(short tipoTelefono) {
		this.tipoTelefono = tipoTelefono;
	}

	@Column(name = "ID_OPERACION", precision = 9, scale = 0)
	public Integer getIdOperacion() {
		return this.idOperacion;
	}

	public void setIdOperacion(Integer idOperacion) {
		this.idOperacion = idOperacion;
	}

	@Column(name = "TELEFONO", length = 50)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "PRE_TELEFONO", length = 10)
	public String getPreTelefono() {
		return this.preTelefono;
	}

	public void setPreTelefono(String preTelefono) {
		this.preTelefono = preTelefono;
	}

	@Column(name = "ID_TIPO", length = 20)
	public String getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(String idTipo) {
		this.idTipo = idTipo;
	}

	@Column(name = "TELEFONO2", length = 50)
	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	@Column(name = "MOVIL", length = 50)
	public String getMovil() {
		return this.movil;
	}

	public void setMovil(String movil) {
		this.movil = movil;
	}

}
