package com.pdr.common.corredora.entity;
// Generated 29-09-2020 15:26:18 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CorrCiudad generated by hbm2java
 */
@Entity
@Table(name = "CORR_CIUDAD", schema = "CDORA")
public class CorrCiudad implements java.io.Serializable {

	private int idCiudad;
	private CorrRegion corrRegion;
	private String descCiudad;
	private Set<CorrComuna> corrComunas = new HashSet<CorrComuna>(0);

	public CorrCiudad() {
	}

	public CorrCiudad(int idCiudad) {
		this.idCiudad = idCiudad;
	}

	public CorrCiudad(int idCiudad, CorrRegion corrRegion, String descCiudad, Set<CorrComuna> corrComunas) {
		this.idCiudad = idCiudad;
		this.corrRegion = corrRegion;
		this.descCiudad = descCiudad;
		this.corrComunas = corrComunas;
	}

	@Id

	@Column(name = "ID_CIUDAD", unique = true, nullable = false, precision = 5, scale = 0)
	public int getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(int idCiudad) {
		this.idCiudad = idCiudad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REGION")
	public CorrRegion getCorrRegion() {
		return this.corrRegion;
	}

	public void setCorrRegion(CorrRegion corrRegion) {
		this.corrRegion = corrRegion;
	}

	@Column(name = "DESC_CIUDAD", length = 50)
	public String getDescCiudad() {
		return this.descCiudad;
	}

	public void setDescCiudad(String descCiudad) {
		this.descCiudad = descCiudad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "corrCiudad")
	public Set<CorrComuna> getCorrComunas() {
		return this.corrComunas;
	}

	public void setCorrComunas(Set<CorrComuna> corrComunas) {
		this.corrComunas = corrComunas;
	}

}
